name: CajasPlugin
version: '1.0 '
main: me.offloner.backpack1.Backpack1
api-version: '1.21'
authors: [ Offloner ]
description: Para que lleves tu caja fuerte a todos lados!
commands:
  caja:
    description: Permite utilizar una caja
    usage: /<command>
