name: VaultsPlugin
version: '1.0'
main: me.offloner.vaultsplugin.VaultsPlugin
api-version: '1.21'
authors: [ Offloner ]
description: You can use a vault
commands:
  caja:
    description: Permite utilizar una caja
    usage: /<command>
  vault:
    description: You can use a vault
    usage: /<command>
